# Generated by Django 2.2.11 on 2020-09-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0031_kc_curve"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agrifield",
            old_name="custom_kc_initial",
            new_name="custom_kc_plantingdate",
        ),
        migrations.RenameField(
            model_name="croptype",
            old_name="kc_initial",
            new_name="kc_plantingdate",
        ),
    ]
