# Generated by Django 2.2.12 on 2020-11-10 09:19

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aira", "0033_profile_supervisor_related_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoRA_ARTAFlowmeter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100)),
                (
                    "flowmeter_water_percentage",
                    models.PositiveSmallIntegerField(
                        help_text=(
                            "Percentage of water that corresponds to the flowmeter (%)"
                        ),
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "conversion_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("6.8"), max_digits=5
                    ),
                ),
                (
                    "report_frequency_in_minutes",
                    models.PositiveSmallIntegerField(default=5),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="appliedirrigation",
            name="is_automatically_reported",
            field=models.BooleanField(
                default=False,
                verbose_name="Is automatically added by a telemetric flowmeter",
            ),
        ),
        migrations.AddConstraint(
            model_name="appliedirrigation",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_automatically_reported=True),
                fields=("supplied_water_volume", "timestamp", "agrifield"),
                name="unique_automatic_flowmeter_irrigations",
            ),
        ),
        migrations.AddField(
            model_name="lora_artaflowmeter",
            name="agrifield",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="aira.Agrifield"
            ),
        ),
    ]
